pipeline {
	agent any
	stages {
		stage('Create a k8s cluster') {
			steps {
				withAWS(region:'us-east-1', credentials:'jenkins_udacity_cloud_devops_capstone') {
					sh '''
						eksctl create cluster \
						--name udacitycapstonecluster14 \
						--version 1.13 \
						--nodegroup-name udacitycapstoneworkers14 \
						--node-type t2.small \
						--nodes 2 \
						--nodes-min 1 \
						--nodes-max 3 \
						--node-ami auto \
						--region us-east-1 \
						--zones us-east-1a \
						--zones us-east-1b \
						--zones us-east-1c \
					'''
				}
			}
		}

		stage('Create a config file') {
			steps {
				withAWS(region:'us-east-1', credentials:'jenkins_udacity_cloud_devops_capstone') {
					sh '''
						aws eks --region us-east-1 update-kubeconfig --name udacitycapstonecluster14
					'''
				}
			}
		}
	}
}
