pipeline {
	agent any
	stages {
		stage('Lint the index.html') {
			steps {
					sh '''
					    tidy blue_green_deploy/*.html
					'''
			}
		}
		stage('Build a docker image') {
			steps {
				withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'udacity_cloud_devops_capstone_dockerhub', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD']]){
					sh '''
						docker build -t mytrgor/udacity_capstone -f blue_green_deploy/Dockerfile .
					'''
				}
			}
		}
		stage('Push the docker image to Dockerhub') {
			steps {
				withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'udacity_cloud_devops_capstone_dockerhub', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD']]){
					sh '''
						docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
						docker push mytrgor/udacity_capstone
					'''
				}
			}
		}

		stage('Set current kubectl context') {
			steps {
				withAWS(region:'us-east-1', credentials:'jenkins_udacity_cloud_devops_capstone') {
					sh '''
						kubectl config use-context arn:aws:eks:us-east-1:474880089665:cluster/udacitycapstonecluster14
					'''
				}
			}
		}
		stage('Apply the blue container') {
			steps {
				withAWS(region:'us-east-1', credentials:'jenkins_udacity_cloud_devops_capstone') {
					sh '''
						kubectl apply -f blue_green_deploy/blue.controller.json
					'''
				}
			}
		}
		stage('Apply the green container') {
			steps {
				withAWS(region:'us-east-1', credentials:'jenkins_udacity_cloud_devops_capstone') {
					sh '''
						kubectl apply -f blue_green_deploy/green.controller.json
					'''
				}
			}
		}
		stage('Apply the blue service within udacitycapstonecluster14') {
			steps {
				withAWS(region:'us-east-1', credentials:'jenkins_udacity_cloud_devops_capstone') {
					sh '''
						kubectl apply -f blue_green_deploy/blue.service.json
					'''
				}
			}
		}
		stage('Wait to redirect the traffic to the green service') {
            steps {
                input "Wait to redirect the traffic to the green service"
            }
        }
		stage('Apply the green service within udacitycapstonecluster14') {
			steps {
				withAWS(region:'us-east-1', credentials:'jenkins_udacity_cloud_devops_capstone') {
					sh '''
						kubectl apply -f blue_green_deploy/green.service.json
					'''
				}
			}
		}
	}
}
